baseURL = "https://margieandchristian.com/"
languageCode = "en-us"
title = "Margie & Christian"
googleAnalytics = "G-ERQ3CYQ3VE"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]
copyright = "&copy; Christian Mendoza. Built with [Hugo](//gohugo.io). GitHub [source](//github.com/christianmendoza/margieandchristian.com)."
enableRobotsTXT = true
verbose = true
verboseLog = true
watch = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 
